### ISSUE TITLE
Other ignore format

### ISSUE THREAD

**Issue by sbrunner** [zb3/zgitignore#3]
Is it possible to also support .dockerignore format?

If you're interested i will create a pull request :-)

**Comment by zb3** [comment]
I didn't even know this project exists :O
Thanks for finding this!

While I am not actively working on this and I don't even know what exactly differs (is it only the `?` sign?), feel free to submit a pull request as long as:
a) by default we still match for `.gitignore` (backward compatibility)
b) there are no external dependencies

Otherwise I think you should fork this and create a "community" version :D

(Of course if it's just a `?` sign I can do this, but don't know when)

**Comment by sbrunner** [comment]
Thanks I will provide a pull request in a couple of weeks :-)
