### ISSUE TITLE
Problem on Python 3.7

### ISSUE THREAD

**Issue by wimglenn** [zb3/zgitignore#6]
In Python 3.7, only characters that can have special meaning in a regular expression are escaped by `re.escape`.  The result of `re.escape('\\')` is changed, and now the test suite is failing.

**Comment by zb3** [comment]
So if I understood it correctly, this only affects tests, right?

I think I've fixed this with https://github.com/zb3/zgitignore/commit/aeba2133b93483ba85bb53bfaca56487545cefde, by making the test itself use the value returned by `re.escape`, so that it works in Python 3.7, but also elsewhere.

Did this fix the issue for you?

**Comment by wimglenn** [comment]
I'm not sure whether it affects the library behaviour or not. I assumed since the behaviour of `re.escape` changed, the library's behaviour would change with certain inputs too, but didn't verify this.

**Comment by zb3** [comment]
Well, AFAIK the purpose of `re.escape` didn't change, it still escapes everything _needed_. Since the library code is using `re.escape` only for building the regex (the output of `convert_pattern` does change, but its meaning doesn't), I think it should work. Actually it has to, otherwise `re.escape` would not fit it's purpose...  The test code was wrong though - it assumed a specific output of `re.escape`, not that a specific input was passed to it.

**Comment by wimglenn** [comment]
Sure - if you're confident, I will close the issue. I was searching for a solution which is implementing the wildmatch behaviour of [gitignore](https://git-scm.com/docs/gitignore) spec exactly, so I think I can't use zgitignore anyway because of the different features.

**Comment by zb3** [comment]
It does implement a superset of that spec (at least in 2014 it did), so you could just fork this library - removing the "z" feature set should be trivial.

Anyway, thanks for reporting the issue :)
